### ISSUE TITLE
Setup login and verify.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [exokitxr/store#7]
## Todo

We already have the login HTML and JS written in other sites, the store is missing this code and currently is hardcoded with avaer's user account.

We need to setup the store with proper login and while doing so should use the `common.js` to perfect and finalize a frontend Exokit API for this common task.

Modular as possbile.

**Comment by avaer** [comment]
Thanks for filing these!

> the store is missing this code and currently is hardcoded with avaer's user account.

It's not hardcoded in the login, it's just the display name.

I agree with the modularity; the way I'd do that is to have a separate site/domain that serves the account logic, at e.g. `https://accounts.exokit.org/accounts.js`. This code is currently inlined to  the different properties in various states of completion, but it could be pulled out and abstracted.
